version: {build}
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: x64
build:
  project: vs/Helios.sln
  verbosity: minimal
before_build:
  cmd: git submodule update --init --recursive
  cmd: vs2017.bat