version: {build}
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: x64
build:
  project: vs/Helios.sln
  verbosity: minimal
before_build:
- git submodule update --init --recursive
- vs2017.bat