version: 0.1.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: x64
build:
  project: vs/Helios.sln
  verbosity: minimal
install:
- git submodule update --init --recursive
before_build:
  cmd: vs2017.bat